"""Terminology aliases for Indian health insurance policy fields.

Maps each schema field to its common synonyms across Indian insurers.
This is fed into extraction prompts so the model recognizes varied terminology.
"""

FIELD_ALIASES = {
    # ── Product Identity ──
    "uin": [
        "UIN",
        "Unique Identification Number",
        "IRDAI UIN",
        "IRDAI registration number",
        "product UIN",
        "HLP number",
    ],
    "product_name": [
        "product name",
        "policy name",
        "plan name",
        "policy title",
        "scheme name",
        "cover name",
        "insurance plan",
    ],
    "network_hospital_count": [
        "network hospitals",
        "empanelled hospitals",
        "cashless hospitals",
        "hospital network count",
        "number of hospitals",
        "hospital network size",
        "network hospital list",
        "cashless facility network",
        "tie-up hospitals",
    ],
    "insurer_name": [
        "insurer name",
        "insurance company name",
        "company name",
        "underwriter",
        "insurance provider",
        "carrier",
    ],
    # ── Coverage Info ──
    "coverage.sum_insured_range": [
        "sum insured",
        "sum assured",
        "cover amount",
        "limit of indemnity",
        "policy limit",
        "maximum liability",
        "capital sum insured",
        "basic sum insured",
        "SI",
        "sum insured options",
        "cover options",
        "plan options",
        "available sum insured slabs",
    ],
    "coverage.sum_insured_type": [
        "individual sum insured",
        "floater sum insured",
        "family floater",
        "individual cover",
        "floater cover",
        "aggregate cover",
    ],
    "coverage.room_rent_type": [
        "room rent type",
        "room category",
        "accommodation charges",
        "bed charges",
        "room and boarding",
        "hospitalisation room charges",
        "room rent entitlement",
        "type of room",
        "ward charges",
    ],
    "coverage.room_rent_limit": [
        "room rent limit",
        "room rent sub-limit",
        "maximum room rent",
        "room charges limit",
        "room rent capping",
        "ward limit",
        "room rent per day",
        "accommodation limit",
        "1% of Sum Insured per day",
        "2% of Sum Insured per day",
        "per day room rent capping",
        "room rent entitlement per day",
        "room rent capping as percentage of SI",
    ],
    "coverage.icu_limit": [
        "ICU limit",
        "intensive care unit limit",
        "ICCU limit",
        "intensive cardiac care unit",
        "CCU",
        "critical care limit",
        "ICU charges limit",
        "maximum ICU per day",
        "ICU rent capping",
        "ICU capping as percentage of SI",
        "2% of Sum Insured per day ICU",
    ],
    "coverage.domiciliary_cover": [
        "domiciliary cover",
        "domiciliary hospitalization",
        "hospitalisation at home",
        "home care treatment",
        "home hospitalization",
        "domiciliary treatment",
        "domiciliary hospitalisation excluded",
        "domiciliary cover not admissible",
    ],
    "coverage.day_care_procedures_included": [
        "day care",
        "daycare procedures",
        "day surgery",
        "one day surgery",
        "ambulatory surgery",
        "same day surgery",
        "outpatient surgery",
    ],
    "coverage.ambulance_cover": [
        "ambulance cover",
        "ambulance charges",
        "ambulance expenses",
        "transportation charges",
        "patient transport",
        "road ambulance",
        "air ambulance",
        "mortuary transport",
    ],
    "coverage.pre_hospitalization_days": [
        "pre-hospitalisation days",
        "pre-hospitalization",
        "days before admission",
        "pre admission days",
        "pre hospital cover",
        "prior to hospitalisation",
    ],
    "coverage.post_hospitalization_days": [
        "post-hospitalisation days",
        "post-hospitalization",
        "days after discharge",
        "post discharge days",
        "follow up cover",
        "recovery period cover",
    ],
    # ── Deductibles ──
    "deductibles.deductible_amount": [
        "deductible amount",
        "deductible",
        "excess amount",
        "compulsory deductible",
        "voluntary deductible",
        "initial amount borne by insured",
        "proportionate deduction",
        "insured shall bear",
        "excess clause",
        "first loss amount",
        "no proportionate deduction optional cover",
    ],
    "deductibles.deductible_type": [
        "compulsory deductible",
        "voluntary deductible",
        "deductible applicable",
        "deductible type",
    ],
    "deductibles.copay_percentage": [
        "co-pay percentage",
        "copayment",
        "co-payment",
        "cost sharing",
        "cost participation",
        "policyholder share",
        "insured share",
        "insured contribution percentage",
        "you shall bear the differential",
        "continue to bear",
        "proportionate deduction percentage",
    ],
    "deductibles.copay_applies_to": [
        "co-pay applies to",
        "copay applicable on",
        "co-payment basis",
        "cost sharing applies to",
        "co-pay on room rent",
        "co-pay on specific items",
        "differential between actual and eligible",
        "room rent differential",
        "co-pay on room rent exceeding limit",
    ],
    "deductibles.copay_conditions": [
        "co-pay conditions",
        "copay terms",
        "age-based co-pay",
        "zone-based co-pay",
        "SI-based co-pay",
        "co-pay for senior citizens",
        "co-pay for specific zones",
        "co-pay only if room rent exceeds limit",
        "waiver of co-pay for cashless",
        "no co-pay if treated in network hospital",
    ],
    # ── Waiting Periods ──
    "waiting_periods.pde_waiting_months": [
        "PED waiting period",
        "pre-existing disease waiting",
        "pre-existing condition waiting",
        "prior condition waiting",
        "PED moratorium",
        "waiting for pre-existing",
        "pre-existing diseases exclusion period",
        "48 months PED waiting",
        "24 months PED waiting",
        "pre-existing disease exclusion waiting",
        "continuous coverage for PED",
        "PED waiting after continuous coverage",
    ],
    "waiting_periods.initial_waiting_period_days": [
        "initial waiting period",
        "first 30 days",
        "initial exclusion period",
        "waiting period for illness",
        "cooling off period",
        "first admission waiting",
        "deferred period",
        "30 days waiting from inception",
        "first 30 days exclusion",
        "no cover for first 30 days",
    ],
    "waiting_periods.specific_disease_waiting_months": [
        "specific disease waiting",
        "specified disease waiting",
        "listed disease waiting",
        "disease specific waiting",
        "named conditions waiting",
        "scheduled disease waiting",
        "waiting period for specific diseases",
        "90 days waiting conditions",
        "24 months waiting conditions",
        "48 months waiting conditions",
        "specific waiting period schedule",
    ],
    "waiting_periods.specific_diseases": [
        "specific disease list",
        "disease waiting schedule",
        "list of diseases with waiting",
        "disease wise waiting",
        "waiting period schedule",
        "specified conditions",
        "named diseases",
        "disease waiting table",
        "90 days waiting list diabetes hypertension cardiac",
        "24 months waiting list cataract hernia",
        "48 months waiting list joint replacement",
    ],
    "waiting_periods.maternity_waiting_months": [
        "maternity waiting period",
        "delivery waiting period",
        "childbirth waiting",
        "waiting period for maternity",
        "maternity benefit waiting",
        "9 months maternity waiting",
        "36 months maternity waiting",
        "maternity optional cover waiting",
    ],
    "waiting_periods.accident_waiting_days": [
        "accident waiting period",
        "waiting period for accident",
        "accident cover waiting",
        "no waiting for accident",
        "accident exclusion from waiting",
    ],
    "waiting_periods.loaded_waiting_days": [
        "loading waiting period",
        "late entry waiting",
        "new entrant waiting",
        "age loading waiting",
        "additional waiting for late entry",
        "waiting for loading due to age",
        "age related additional waiting",
    ],
    # ── Maternity ──
    "maternity.covered": [
        "maternity cover",
        "maternity benefit",
        "maternity coverage",
        "delivery cover",
        "childbirth cover",
        "maternity expenses benefit",
        "optional cover maternity",
        "optional cover II maternity",
        "delivery benefit",
        "maternity optional cover",
    ],
    "maternity.waiting_months": [
        "maternity waiting period",
        "delivery waiting",
        "maternity benefit waiting",
        "9 months waiting for maternity",
        "36 months waiting for maternity",
        "maternity optional cover waiting months",
    ],
    "maternity.sum_insured_limit": [
        "maternity limit",
        "maternity sub-limit",
        "delivery limit",
        "maximum maternity cover",
        "maternity sum insured",
        "maternity capping",
        "10% of average SI for maternity",
        "maternity benefit limit as percentage of SI",
    ],
    "maternity.preconception_days": [
        "pre-conception days",
        "pre natal days",
        "pregnancy cover days",
        "antenatal cover",
        "antenatal expenses",
        "pre natal expenses not covered unless hospitalised",
    ],
    "maternity.postnatal_days": [
        "post-natal days",
        "post natal days",
        "post delivery cover",
        "postnatal expenses",
        "newborn care days",
        "post natal expenses not covered unless hospitalised",
    ],
    "maternity.newborn_cover": [
        "newborn cover",
        "newborn baby cover",
        "neonatal cover",
        "baby cover from birth",
        "newborn from day 1",
        "new born baby coverage",
        "baby born during policy period",
    ],
    "maternity.newborn_cover_days": [
        "newborn cover days",
        "newborn coverage period",
        "days from birth covered",
        "newborn coverage duration",
        "from date of birth till policy expiry",
        "newborn cover for current policy year only",
    ],
    "maternity.vaccination_cover": [
        "vaccination cover",
        "immunization cover",
        "newborn vaccination",
        "baby vaccination",
        "newborn immunisation",
    ],
    "maternity.delivery_types_covered": [
        "delivery types covered",
        "normal delivery",
        "C-section",
        "caesarean section",
        "cesarean delivery",
        "types of childbirth covered",
        "normal and caesarean delivery",
        "delivery first two children only",
    ],
    "maternity.first_child_limit": [
        "first child limit",
        "1st child limit",
        "first child maternity",
        "cover for first delivery",
        "first two children covered",
    ],
    "maternity.second_child_limit": [
        "second child limit",
        "2nd child limit",
        "second child maternity",
        "cover for subsequent delivery",
        "first two children only",
    ],
    # ── Sub-Limits ──
    "sub_limits.disease_specific": [
        "disease sub-limits",
        "disease specific limits",
        "treatment specific sub-limits",
        "procedure limits",
        "illness wise sub-limit",
        "condition specific limit",
        "cataract limit",
        "stone treatment limit",
        "hernia limit",
        "specific procedure sub-limit",
        "10% of SI sub-limit for cataract",
        "sub-limit expressed as percentage of SI",
        "X% of Sum Insured sub-limit for",
    ],
    "sub_limits.surgical_procedures": [
        "surgical sub-limits",
        "surgery limits",
        "surgical procedure limits",
        "operation limits",
        "surgery wise sub-limit",
        "surgical procedure capping",
        "limit per surgical procedure",
    ],
    "sub_limits.annual_health_checkup": [
        "annual health checkup",
        "preventive health checkup",
        "wellness checkup",
        "health screening",
        "annual medical checkup",
        "routine checkup",
        "free health checkup after no claim",
    ],
    "sub_limits.specific_benefits": [
        "specific benefits",
        "other benefits",
        "additional benefits",
        "value added benefits",
        "special benefits",
        "hospital cash",
        "critical care benefit",
        "recovery benefit",
        "convalescence benefit",
        "health checkup benefit",
        "hospital cash 0.1% of SI per day",
        "critical care benefit 10% of SI once",
    ],
    "sub_limits.modern_treatment_sub_limits": [
        "modern treatment limits",
        "modern treatment sub-limits",
        "robotic surgery limit",
        "laser treatment limit",
        "keyhole surgery limit",
        "laparoscopic limit",
        "radio surgery limit",
        "stereotactic limit",
        "minimally invasive procedure limit",
        "advanced treatment sub-limit",
        "cataract surgery limit",
        "HIFU",
        "radiofrequency ablation",
        "section 3.15 modern treatments",
        "coverage for modern treatments or procedures",
        "modern treatment table with limits",
    ],
    # ── Exclusions ──
    "exclusions.permanent_exclusions": [
        "permanent exclusions",
        "always excluded",
        "general exclusions",
        "standard exclusions",
        "absolute exclusions",
        "what is not covered",
        "exclusions applicable",
    ],
    "exclusions.waiting_period_exclusions": [
        "waiting period exclusions",
        "time bound exclusions",
        "initial exclusions",
        "deferred conditions",
        "exclusions during waiting period",
    ],
    "exclusions.general_exclusions": [
        "general exclusions",
        "other exclusions",
        "exclusions list",
        "specific exclusions",
        "conditions not covered",
    ],
    "exclusions.notes": [
        "exclusion notes",
        "important notes on exclusions",
        "exclusion caveats",
        "moratorium provision",
        "moratorium period",
        "8 year moratorium",
        "portability exclusion notes",
    ],
    # ── No Claim Bonus ──
    "no_claim_bonus.ncb_type": [
        "NCB type",
        "no claim bonus type",
        "cumulative bonus type",
        "claim free bonus",
        "no claim discount",
        "sum insured increase",
        "SI enhancement",
        "cumulative bonus in Indian insurance IS the NCB",
        "CB type",
        "cumulative bonus percentage increase",
        "no claim benefit",
    ],
    "no_claim_bonus.increase_percentage_per_year": [
        "NCB increase per year",
        "annual NCB percentage",
        "yearly bonus increase",
        "annual SI enhancement",
        "bonus accumulation rate",
        "cumulative bonus increased by X% each renewal",
        "CB increase per claim free year",
        "annual cumulative bonus rate",
    ],
    "no_claim_bonus.max_ncb_percentage": [
        "maximum NCB",
        "NCB cap",
        "max cumulative bonus",
        "bonus ceiling",
        "maximum SI enhancement",
        "cumulative bonus subject to maximum of X%",
        "CB maximum percentage",
        "cumulative bonus capping",
    ],
    "no_claim_bonus.restoration_benefit": [
        "restoration benefit",
        "reinstatement of cover",
        "recharge benefit",
        "refill benefit",
        "sum insured restoration",
        "auto restoration",
        "automatic restoration of SI",
        "compassionate recharge",
        "sum insured reinstatement on exhaustion",
    ],
    "no_claim_bonus.restoration_details": [
        "restoration details",
        "restoration conditions",
        "recharge conditions",
        "how many restorations",
        "same illness restoration",
        "unlimited restoration",
        "one time restoration",
        "restoration for different illness only",
        "restoration for same illness also covered",
    ],
    "no_claim_bonus.cumulative_bonus_type": [
        "cumulative bonus type",
        "bonus accumulation",
        "how bonus works",
        "bonus applicable to",
        "floater bonus",
        "individual bonus",
        "CB on floater basis",
        "CB on individual basis",
        "cumulative bonus added to family floater",
        "cumulative bonus per insured person",
    ],
    # ── Eligibility ──
    "eligibility.min_entry_age_main": [
        "minimum entry age",
        "minimum age for insured",
        "minimum age at entry",
        "entry age minimum",
        "lowest entry age",
        "min age for insurance",
        "age at entry minimum",
        "entry age 18 years",
        "minimum age at inception",
    ],
    "eligibility.max_entry_age_main": [
        "maximum entry age",
        "maximum age at entry",
        "entry age maximum",
        "highest entry age",
        "max age for new policy",
        "age 65 at entry",
        "entry age limit 65",
        "max age for new entrant",
        "entry age up to 65 years",
        "age limit at inception",
    ],
    "eligibility.max_renewal_age": [
        "maximum renewal age",
        "lifelong renewal",
        "renewal up to age",
        "age limit for renewal",
        "cover till age",
        "renewable up to age 80",
        "renewable up to age 99",
        "lifelong renewability",
        "cover available up to age",
        "renewal age limit",
    ],
    "eligibility.min_entry_age_dependent": [
        "minimum age for dependent",
        "dependent min age",
        "child minimum age",
        "youngest dependent age",
        "minimum age for child",
        "dependent child age 3 months",
        "age from 3 months for dependent",
    ],
    "eligibility.max_entry_age_dependent": [
        "maximum age for dependent",
        "dependent max age",
        "child maximum age",
        "oldest dependent age",
        "dependent age limit",
        "dependent child up to 25 years",
        "age limit for dependent children",
        "dependent student age limit",
    ],
    "eligibility.max_number_of_dependents": [
        "maximum dependents",
        "max family members",
        "maximum number of children",
        "dependent limit",
        "maximum insured members",
        "maximum number of dependents covered",
        "family size limit",
    ],
    "eligibility.dependent_relationship_types": [
        "dependent types",
        "eligible dependents",
        "family definition",
        "who can be covered",
        "spouse children parents",
        "dependents covered",
        "family members covered",
        "spouse parents in law",
        "spouse dependent children parents",
        "family unit definition",
    ],
    # ── Portability ──
    "portability.allowed": [
        "portability allowed",
        "portable",
        "can port",
        "migration allowed",
        "transfer allowed",
        "option to port to other insurers",
        "section 5.15 portability and migration",
    ],
    "portability.conditions": [
        "portability conditions",
        "portability terms",
        "migration terms",
        "portability notice period",
        "portability procedure",
        "45 days before renewal for portability",
        "30 days before renewal for migration",
        "port at least 45 days before renewal",
    ],
    "portability.waiting_period_waived": [
        "portability waiting waiver",
        "portability continuity",
        "prior coverage credit",
        "waiting period reduction",
        "portability waiting waived",
        "continuity benefits preserved on portability",
        "accrued waiting period credit on port",
    ],
    # ── Policy Terms ──
    "policy_terms.policy_term_years": [
        "policy term",
        "policy period",
        "cover period",
        "policy duration",
        "insurance term",
        "one year policy",
        "two year policy",
        "period of insurance",
    ],
    "policy_terms.free_look_period_days": [
        "free look period",
        "free look days",
        "review period",
        "cancellation period",
        "cooling off days",
        "return policy period",
        "15 days free look",
        "free look at inception of first policy",
    ],
    "policy_terms.grace_period_days": [
        "grace period",
        "grace days",
        "renewal grace",
        "premium grace period",
        "late payment grace",
        "30 days grace period",
        "15 days grace period",
        "grace period for renewal",
    ],
    "policy_terms.cancellation_allowed_by_insurer": [
        "insurer cancellation",
        "company cancellation",
        "cancellation by insurer",
        "policy cancellation by company",
        "15 days notice for cancellation",
        "we may cancel on non cooperation",
    ],
    "policy_terms.cancellation_allowed_by_policyholder": [
        "policyholder cancellation",
        "insured cancellation",
        "cancellation by insured",
        "surrender of policy",
        "you may cancel at any time",
        "policyholder right to cancel",
    ],
    "policy_terms.refund_on_cancellation": [
        "refund on cancellation",
        "cancellation refund",
        "premium refund",
        "short period rate",
        "refund terms",
        "refund at short period scale",
        "1/4th annual rate up to 1 month",
        "proportionate risk premium deduction",
    ],
    "policy_terms.reinstatement_period_days": [
        "reinstatement period",
        "revival period",
        "policy revival",
        "renewal late period",
        "reinstatement days",
        "30 days for reinstatement",
        "break in policy 30 days",
    ],
    "policy_terms.reinstatement_conditions": [
        "reinstatement conditions",
        "revival conditions",
        "policy revival terms",
        "reinstatement terms",
        "reinstatement within 30 days of expiry",
    ],
    "policy_terms.pro_rata_treatment": [
        "pro rata treatment",
        "pro-rata cover",
        "proportionate deduction",
        "daily pro-rata",
        "pro rata refund",
        "short period scale table",
        "proportionate risk premium",
    ],
    "policy_terms.location_coverage": [
        "location coverage",
        "geographical coverage",
        "territorial scope",
        "worldwide cover",
        "India cover",
        "global cover",
        "coverage area",
        "treatment within India only",
        "India territorial limit",
    ],
    # ── Claims ──
    "claims.claim_intimation_window": [
        "claim intimation",
        "claim notification",
        "claim reporting time",
        "notice of claim",
        "intimation period",
        "claim reporting period",
        "how soon to inform",
        "48 hours before planned hospitalisation",
        "24 hours for emergency hospitalisation",
        "intimate TPA within 24 hours",
        "immediate notification of claim",
        "claim intimation within 24 hours of admission",
    ],
    "claims.cashless_network": [
        "cashless network",
        "network hospitals",
        "cashless facility",
        "network provider",
        "TPA network",
        "empanelled hospitals",
        "hospital network",
        "preferred provider network PPN",
        "cashless hospital list",
    ],
    "claims.reimbursement_allowed": [
        "reimbursement",
        "reimbursement claim",
        "claim reimbursement",
        "pay and claim",
        "reimbursement mode available",
        "cashless or reimbursement",
    ],
    "claims.pre_authorization_required": [
        "pre-authorization",
        "pre authorisation",
        "prior approval",
        "pre admission approval",
        "authorization for cashless",
        "cashless requires pre authorisation",
        "pre auth required for cashless",
    ],
    "claims.discharge_process": [
        "discharge process",
        "claim settlement process",
        "claim procedure",
        "how to claim",
        "claim submission",
        "documentation for claim",
        "submit documents within 7 days of discharge",
        "claim documents submission process",
    ],
    "claims.claim_settlement_tat": [
        "claim settlement TAT",
        "claim turnaround time",
        "settlement time",
        "claim processing time",
        "claim payment timeline",
        "TAT for settlement",
        "settle within 30 days of last document",
        "45 days if investigation required",
        "interest at 2% above bank rate for delay",
    ],
    "claims.required_documents_for_claim": [
        "claim documents",
        "documents required",
        "claim paperwork",
        "required documents",
        "documents for reimbursement",
        "hospital bill and discharge certificate",
        "cash memos and prescriptions",
        "surgeon certificate and bills",
        "attending doctor certificate",
    ],
    # ── Additional Features ──
    "additional_features.wellness_benefits": [
        "wellness benefits",
        "wellness program",
        "wellness discount",
        "fitness benefit",
        "health and wellness",
        "wellness and health screening",
        "preventive wellness benefit",
    ],
    "additional_features.annual_health_checkup": [
        "annual health checkup",
        "free health checkup",
        "preventive checkup",
        "wellness checkup",
        "health screening",
        "periodic checkup",
        "no claim bonus health checkup",
    ],
    "additional_features.alternative_treatment_cover": [
        "alternative treatment",
        "AYUSH cover",
        "ayurveda cover",
        "homeopathy cover",
        "unani cover",
        "siddha cover",
        "naturopathy cover",
        "non allopathic treatment",
        "section 3.4 AYUSH treatment",
        "treatments under ayurvedic homeopathic unani",
    ],
    "additional_features.alternative_treatment_limit": [
        "alternative treatment limit",
        "AYUSH limit",
        "ayurvedic treatment sub-limit",
        "AYUSH sub-limit",
        "25% of Sum Insured for AYUSH",
        "AYUSH limit as percentage of SI",
    ],
    "additional_features.oopd_cover": [
        "OPD cover",
        "outpatient cover",
        "outpatient department",
        "OPD expenses",
        "outpatient consultation",
        "OPD treatment not covered",
        "outpatient treatment excluded",
    ],
    "additional_features.dental_cover": [
        "dental cover",
        "dental treatment",
        "dental expenses",
        "dental care",
        "dental treatment excluded unless accident",
        "dental surgery only if accident",
    ],
    "additional_features.optical_cover": [
        "optical cover",
        "vision cover",
        "eyewear cover",
        "spectacles cover",
        "contact lens cover",
        "refractive error excluded",
        "spectacles and contact lenses excluded",
    ],
    "additional_features.organ_donor_expenses": [
        "organ donor cover",
        "organ donor expenses",
        "transplant donor cover",
        "donor expenses",
        "organ transplant donor",
        "medical expenses for organ donor",
        "donor hospitalisation expenses covered",
    ],
    "additional_features.co_pay_waiver_for_cashless": [
        "co-pay waiver",
        "copay waiver for cashless",
        "waiver of co-payment",
        "no copay if cashless",
        "co-pay not applicable in network hospital",
        "optional cover no proportionate deduction",
    ],
    "additional_features.modern_treatment_cover": [
        "modern treatment cover",
        "advanced treatment",
        "robotic surgery cover",
        "laser treatment cover",
        "keyhole surgery",
        "minimally invasive procedure",
        "stereotactic surgery",
        "HIFU treatment",
        "radiofrequency ablation",
        "brachytherapy",
        "immunotherapy",
        "oral chemotherapy",
        "section 3.15 coverage for modern treatments",
        "modern treatments or procedures list",
    ],
    "additional_features.consumables_cover": [
        "consumables cover",
        "surgical consumables",
        "implants cover",
        "prosthetics cover",
        "medical consumables",
        "disposables cover",
        "cost of prosthetic devices implanted during surgery",
        "pacemaker implants covered",
    ],
    "additional_features.nc_age_load": [
        "new entrant age loading",
        "age loading",
        "additional premium for age",
        "age related loading",
        "new policy age loading",
        "additional premium loading for age at entry",
        "age based premium loading",
    ],
}
